/*
** EPITECH PROJECT, 2023
** Epitech_Plazza
** File description:
** ConditonalVariable
*/

#ifndef EPITECH_PLAZZA_CONDITONALVARIABLE_HPP
#define EPITECH_PLAZZA_CONDITONALVARIABLE_HPP

#endif //EPITECH_PLAZZA_CONDITONALVARIABLE_HPP
